language: objective-c
env:
  - OS=6.1
  - OS=7.0
rvm: 1.9.3
before:
  - brew update
  - bundle install
  - bundle exec pod install
script: xcodebuild -workspace XNGOAuth1Client.xcworkspace -scheme 'XNGOAuth1Client' -destination platform='iOS Simulator',OS=$OS,name='iPhone Retina (4-inch)' clean build test -sdk iphonesimulator | xcpretty -c
